version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ormgpt
      POSTGRES_USER: mysecretuser
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    restart: unless-stopped
  db2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: ormgpt
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
        - ./.docker/mysql:/var/lib/mysql